import { Movie } from './src/core/models/movie';

export const sampleMovies: Movie[] = [
  {
    id: '1',
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    releaseYear: 1994,
    genre: 'Drama',
    rating: 9.3,
    favorite: true,
  },
  {
    id: '2',
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    releaseYear: 1972,
    genre: 'Crime',
    rating: 9.2,
    favorite: false,
  },
  {
    id: '3',
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    releaseYear: 2008,
    genre: 'Action',
    rating: 9.0,
    favorite: true,
  },
  {
    id: '4',
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    releaseYear: 1994,
    genre: 'Crime',
    rating: 8.9,
    favorite: true,
  },
  {
    id: '5',
    title: 'The Lord of the Rings: The Return of the King',
    director: 'Peter Jackson',
    releaseYear: 2003,
    genre: 'Adventure',
    rating: 8.9,
    favorite: false,
  },
  {
    id: '6',
    title: "Schindler's List",
    director: 'Steven Spielberg',
    releaseYear: 1993,
    genre: 'Drama',
    rating: 8.9,
    favorite: false,
  },
  {
    id: '7',
    title: 'Inception',
    director: 'Christopher Nolan',
    releaseYear: 2010,
    genre: 'Sci-Fi',
    rating: 8.8,
    favorite: true,
  },
  {
    id: '8',
    title: 'Fight Club',
    director: 'David Fincher',
    releaseYear: 1999,
    genre: 'Drama',
    rating: 8.8,
    favorite: false,
  },
  {
    id: '9',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    director: 'Peter Jackson',
    releaseYear: 2001,
    genre: 'Adventure',
    rating: 8.8,
    favorite: false,
  },
  {
    id: '10',
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    releaseYear: 1994,
    genre: 'Comedy',
    rating: 8.8,
    favorite: false,
  },
  {
    id: '11',
    title: 'Goodfellas',
    director: 'Martin Scorsese',
    releaseYear: 1990,
    genre: 'Crime',
    rating: 8.7,
    favorite: false,
  },
  {
    id: '12',
    title: 'The Matrix',
    director: 'The Wachowskis',
    releaseYear: 1999,
    genre: 'Sci-Fi',
    rating: 8.7,
    favorite: false,
  },
  {
    id: '13',
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    director: 'Irvin Kershner',
    releaseYear: 1980,
    genre: 'Sci-Fi',
    rating: 8.7,
    favorite: false,
  },
];
